// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzbvflehqgknmzaywcsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YnZmbGVocWdrbm16YXl3Y3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTE1MjQsImV4cCI6MjA3NDA4NzUyNH0.PE8rtOBjwEjAJbTX33WUZrluvcCtMAWpdULRQW-6k8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});